class AccessorItm < Sequel::Model
  # sequel-annotate: accessors

  # @!attribute accessor_itm
  # @return [AccessorItm]

  # @!attribute category_id
  # @return [Integer]

  # @!attribute id
  # @return [Integer]

  # @!attribute in_stock
  # @return [TrueClass,FalseClass]

  # @!attribute m2mothers
  # @return [Array<AccessorItm>]

  # @!attribute m2o
  # @return [AccessorItm]

  # @!attribute manufacturer_location
  # @return [String]

  # @!attribute manufacturer_name
  # @return [String]

  # @!attribute name
  # @return [String]

  # @!attribute o2m_scls
  # @return [Array<AccessorItm>]

  # @!attribute o2m_tcls
  # @return [Array<AccessorItm>]

  # @!attribute price
  # @return [Float]

  # sequel-annotate: endaccessors
end

# Table: items
# Columns:
#  id                    | integer               | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  category_id           | integer               | NOT NULL
#  manufacturer_name     | character varying(50) |
#  manufacturer_location | text                  |
#  in_stock              | boolean               | DEFAULT false
#  name                  | text                  | DEFAULT 'John'::text
#  price                 | double precision      | DEFAULT 0
# Indexes:
#  items_pkey        | PRIMARY KEY btree (id)
#  name              | UNIQUE btree (manufacturer_name, manufacturer_location)
#  manufacturer_name | btree (manufacturer_name)
# Check constraints:
#  pos_id | (id > 0)
# Foreign key constraints:
#  items_category_id_fkey       | (category_id) REFERENCES categories(id)
#  items_manufacturer_name_fkey | (manufacturer_name, manufacturer_location) REFERENCES manufacturers(name, location)
# Triggers:
#  valid_price | BEFORE INSERT OR UPDATE ON items FOR EACH ROW EXECUTE FUNCTION valid_price()
